template-arb-file: app_pt.arb

arb-dir: lib/src/localization
output-dir: lib/src/localization/generated
output-localization-file: l10n.dart
synthetic-package: false
nullable-getter: false

untranslated-messages-file: untranslated_messages.txt
