// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQapXuzW_-GAk4AT3A5puwOKb35E04_7M',
    appId: '1:1072387025756:web:fd0beec0fd77155b6caf99',
    messagingSenderId: '1072387025756',
    projectId: 'ficha-3det-victory',
    authDomain: 'ficha-3det-victory.firebaseapp.com',
    storageBucket: 'ficha-3det-victory.appspot.com',
    measurementId: 'G-04B2G8NE93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdpl30lfTct3YKNyONfYZd2KvHaCChM4c',
    appId: '1:1072387025756:android:141796b2938152796caf99',
    messagingSenderId: '1072387025756',
    projectId: 'ficha-3det-victory',
    storageBucket: 'ficha-3det-victory.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqMfj9OFAvH8WY3fDRC8b-HiStr3Qg2Sg',
    appId: '1:1072387025756:ios:716cad5bb8f15f5c6caf99',
    messagingSenderId: '1072387025756',
    projectId: 'ficha-3det-victory',
    storageBucket: 'ficha-3det-victory.appspot.com',
    iosBundleId: 'com.nebraska.ficha3detVictory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqMfj9OFAvH8WY3fDRC8b-HiStr3Qg2Sg',
    appId: '1:1072387025756:ios:f08a83c12cad4d576caf99',
    messagingSenderId: '1072387025756',
    projectId: 'ficha-3det-victory',
    storageBucket: 'ficha-3det-victory.appspot.com',
    iosBundleId: 'com.nebraska.ficha3detVictory.RunnerTests',
  );
}
